# Generated by Django 4.2.7 on 2023-11-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytree', '0001_initial'),
        ('extended_tree_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTreeNode',
            fields=[
                ('treenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytree.treenode')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'new_treenode',
            },
            bases=('mytree.treenode',),
        ),
    ]
