# Generated by Django 4.2.7 on 2023-11-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytree', '0002_tree'),
        ('extended_tree_app', '0002_newtreenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedTree',
            fields=[
                ('tree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytree.tree')),
                ('additional_info', models.CharField(blank=True, max_length=200)),
            ],
            bases=('mytree.tree',),
        ),
    ]
