# Generated by Django 4.2.7 on 2023-11-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytree', '0003_remove_tree_root_tree_root_content_type_and_more'),
        ('extended_tree_app', '0003_extendedtree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree2',
            fields=[
                ('tree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytree.tree')),
                ('additional_info', models.CharField(blank=True, max_length=200)),
            ],
            bases=('mytree.tree',),
        ),
        migrations.RenameModel(
            old_name='ExtendedTree',
            new_name='Tree1',
        ),
        migrations.RenameModel(
            old_name='NewTreeNode',
            new_name='TreeNode1',
        ),
        migrations.RenameModel(
            old_name='ExtendedTreeNode',
            new_name='TreeNode2',
        ),
        migrations.RenameField(
            model_name='treenode1',
            old_name='description',
            new_name='extra_data',
        ),
        migrations.RenameField(
            model_name='treenode2',
            old_name='extra_data',
            new_name='description',
        ),
        migrations.AlterModelTable(
            name='treenode1',
            table='treenode1',
        ),
        migrations.AlterModelTable(
            name='treenode2',
            table='treenode2',
        ),
    ]
