# Generated by Django 4.2.7 on 2023-11-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_tree_app', '0004_tree2_rename_extendedtree_tree1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree1',
            old_name='additional_info',
            new_name='additional_info1',
        ),
        migrations.RenameField(
            model_name='tree2',
            old_name='additional_info',
            new_name='additional_info2',
        ),
    ]
