# Generated by Django 4.2.7 on 2023-11-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_tree_app', '0006_rename_extra_data_treenode1_extra_data1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree1',
            name='additional_info1',
        ),
        migrations.RemoveField(
            model_name='tree2',
            name='additional_info2',
        ),
    ]
