# Generated by Django 4.2.7 on 2023-11-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytree', '0003_remove_tree_root_tree_root_content_type_and_more'),
        ('extended_tree_app', '0007_remove_tree1_additional_info1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree3',
            fields=[
                ('tree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytree.tree')),
            ],
            bases=('mytree.tree',),
        ),
        migrations.CreateModel(
            name='TreeNode3',
            fields=[
                ('treenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mytree.treenode')),
                ('extra_data3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'treenode3',
            },
            bases=('mytree.treenode',),
        ),
    ]
