# Generated by Django 4.2.7 on 2023-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_tree_app', '0008_tree3_treenode3'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenode3',
            name='neofield',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
